"""empty message

Revision ID: 99b593597fa1
Revises: 
Create Date: 2024-06-22 16:05:53.820742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b593597fa1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Data', sa.DateTime(), nullable=True),
    sa.Column('Km', sa.Float(), nullable=True),
    sa.Column('Tanque', sa.Float(), nullable=True),
    sa.Column('Valorporlitro', sa.Float(), nullable=True),
    sa.Column('KmTotal', sa.Float(), nullable=True),
    sa.Column('Media', sa.Float(), nullable=True),
    sa.Column('Totalgasolina', sa.Float(), nullable=True),
    sa.Column('Cidadeestrada', sa.String(length=50), nullable=True),
    sa.Column('Posto', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=True),
    sa.Column('vlrkm', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('veiculo',
    sa.Column('idveiculo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Marca', sa.String(length=50), nullable=True),
    sa.Column('Modelo', sa.String(length=50), nullable=True),
    sa.Column('consumo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['consumo_id'], ['consumo.id'], ),
    sa.PrimaryKeyConstraint('idveiculo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veiculo')
    op.drop_table('consumo')
    # ### end Alembic commands ###
